namespace AwgenCore.Voxel
{
  /// <summary>
  /// A special kind of "air" block that is generated by default into newly
  /// created chunks.
  /// </summary>
  public class VoidBlock : BlockType
  {
    public VoidBlock() : base("void", "awgen")
    {
    }


    /// <inheritdoc/>
    public override bool OccludesSurface(Direction direction)
    {
      return false;
    }
  }
}
